# Generated by Django 4.2.5 on 2023-09-14 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatingMandatesMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_information', models.TextField()),
                ('link_more_information', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constituencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True)),
                ('seat_of_commission', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('number_of_mandates', models.SmallIntegerField()),
                ('number_of_voters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=255, unique=True)),
                ('is_coalition', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=255)),
                ('years_of_life', models.CharField(max_length=50)),
                ('short_information', models.TextField()),
                ('more_information', models.TextField()),
                ('link_photo', models.TextField(null=True)),
                ('link_biography', models.TextField(null=True)),
                ('allocating_mandates_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='walks_and_talks.allocatingmandatesmethods')),
            ],
        ),
        migrations.CreateModel(
            name='DemocracyPositiveOpinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(unique=True)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walks_and_talks.people')),
            ],
        ),
        migrations.CreateModel(
            name='DemocracyNegativeOpinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(unique=True)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walks_and_talks.people')),
            ],
        ),
        migrations.CreateModel(
            name='AllocatingMethodsDisadvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disadvantage', models.TextField()),
                ('methods', models.ManyToManyField(to='walks_and_talks.allocatingmandatesmethods')),
            ],
        ),
        migrations.CreateModel(
            name='AllocatingMethodsAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.TextField()),
                ('methods', models.ManyToManyField(to='walks_and_talks.allocatingmandatesmethods')),
            ],
        ),
    ]
